### ISSUE TITLE
Add option to disable CSV logging in order to mitigate warnings about Bukkit API call in asynchronous task

### ISSUE THREAD

**Issue by nejento** [TheViperShow/SystemInfo#10]
On 1.17 my console is getting spammed warnings about Bukkit API call in asynchronous task:
```[17:44:29] [Craft Scheduler Thread - 18/WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 7
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-53]
     at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
     at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-53]
     at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
     at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
     at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
     at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
     at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-53]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-53]
     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-53]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
     at java.lang.Thread.run(Thread.java:831) [?:?]
```

I get that this would need a bigger rewrite, but adding a config with simple switch to disable CSV logging would be handy as it would easily stop generating big CSV files hogging up space on disk. 

Tested on Spigot & Paper 1.17 latest builds on Java OpenJDK 16

**Comment by nejento** [comment]
#11 Possible solution with config and setting to disable CSV logging
