### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by AshKetchumPL** [TheViperShow/SystemInfo#12]
there is the error
`[14:15:17 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:15:27 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:15:37 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:15:47 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:15:57 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:16:07 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:16:17 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:16:27 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:16:37 WARN]: [SystemInfo] Plugin SystemInfo v1.3.5 generated an exception while executing task 9
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-75]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2091) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1185) ~[patched_1.17.jar:git-Paper-75]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$null$0(CSVLogger.java:55) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at studio.thevipershow.systeminfo.csvwriter.CSVLogger.lambda$startLogging$2(CSVLogger.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-75]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by Cyber24-Dr** [comment]
Is not Compatibly with MC 1.17

**Comment by nejento** [comment]
#10 #11 This pull request adds an option to disable the function. You just have to compile it yourself.

**Comment by AshKetchumPL** [comment]
oh oke
