### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by seema84** [TheViperShow/SystemInfo#6]
Paper 1.16.4
System Info Version: 1.1.0

i get this warning when the server is shutting down ->

[15:38:44] [Server thread/INFO]: [SystemInfo] Disabling SystemInfo v1.1.0
[15:38:44] [Server thread/WARN]: java.io.IOException: No such file or directory
[15:38:44] [Server thread/WARN]: 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
[15:38:44] [Server thread/WARN]: 	at java.base/java.io.File.createNewFile(File.java:1026)
[15:38:44] [Server thread/WARN]: 	at studio.thevipershow.systeminfo.csvwriter.CSVLogger.stopLogging(CSVLogger.java:60)
[15:38:44] [Server thread/WARN]: 	at studio.thevipershow.systeminfo.SystemInfo.onDisable(SystemInfo.java:55)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[15:38:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435)
[15:38:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:770)
[15:38:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704)
[15:38:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1044)
[15:38:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[15:38:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by TheViperShow** [comment]
Thank you for reporting this issue. I was already aware of it and it will be fixed in the upcoming version. It is not dangerous and for now you can just ignore that.

**Comment by TheViperShow** [comment]
@seema84 I have released version 1.1.1 on SpigotMC and here on GitHub releases.
Could you please try updating and verify that this same issue has been fixed?

**Comment by seema84** [comment]
yes I will do that in a moment

**Comment by seema84** [comment]
looks good in version 1.2.1
